### no arguments
GET http://localhost:8080/issues
### multiple ids
GET http://localhost:8080/issues?id=hgfchfc&id=dfghjdg&status=resolved
### one id
GET http://localhost:8080/issues?id=hgfchfc
### lots of things
GET http://localhost:8080/issues?id=hgfchfc&id=dfghjdg&status=resolved&projection=title&projection=id&projection=description
